config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'contact' => 'static_pages#contact'
  get 'about' => 'static_pages#about'
  resources :rankers
  resources :schools
  resources :rankings
  resources :votes

end

app/models/ranker.rb
class Ranker < ActiveRecord::Base
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :firstName, presence: true, length: { maximum: 50 }
  validates :lastName, presence: true, length: { maximum: 50 }
  validates :rankAccess, presence: true
  has_secure_password
  validates :password, confirmation: true
end

app/models/ranking.rb
class Ranking < ActiveRecord::Base
  has_many :votes
  has_many :rankers, through: :votes
  validates :rankingTitle, presence: true, length: { maximum: 50 }
  validates :gender, presence: true, length: { maximum: 50 }
  validates :classification, presence: true, length: { maximum: 10 }
  validates :deadline, presence: true
  validates :publishDate, presence: true
  validates :voteTotal, presence: true, length: { maximum: 50 }
  validate :validateDateTime
  
  private
  def validateDateTime
    if deadline != nil && publishDate != nil
    if deadline > publishDate
      errors.add(:deadline, "must be before or same as publish date")
    end
    end
  end
end

app/models/school.rb
class School < ActiveRecord::Base
 scope :'2A', -> {
  where(:classification => "2A")
}
 scope :'4A', -> {
  where(:classification => "4A")
}
  scope :'3A', -> {
  where(:classification => "3A")
}
scope :'1A', -> {
  where(:classification => "1A")
}
  
  
  validates :schoolName, presence: true, length: { maximum: 50 }
  validates :classification, presence: true, length: { maximum: 50 }
  validates :displayName, presence: true, length: { maximum: 50 }
  validates :cooperativeSchool, length: { maximum: 50 }
  validates :active, presence: true, length: { maximum: 5 }
 
 
end
 

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :ranker
  belongs_to :ranking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "Hello World"
  end
  
end

app/controllers/rankers_controller.rb
class RankersController < ApplicationController
  
  wrap_parameters :ranker, include: [:firstName, :lastName, :email, :password, :password_confirmation, :rankAccess, :active]
  def new
    @ranker = Ranker.new
  end
  
  def edit
    @ranker = Ranker.find(params[:id])
  end
  
  def update
    @ranker = Ranker.find(params[:id])
    if @ranker.update_attributes(ranker_params)
      redirect_to @ranker
    else
      render 'edit'
    end
  end

  def index
    @rankers = Ranker.all
  end
  
  def show
    @ranker = Ranker.find(params[:id])
  end
  
  def destroy 
   Ranker.find(params[:id]).destroy
   flash[:success ]="Ranker deleted successively!"
    redirect_to rankers_url
  end
  
  def create
    @ranker = Ranker.new(ranker_params)    
    if @ranker.save
      flash[:success] = "Welcome to the Ranking App!"
      redirect_to @ranker   
    else
      render 'new'
    end
  end
    private

    def ranker_params
      params.require(:ranker).permit(:firstName, :lastName, :email, :password, :password_confirmation, :rankAccess, :active)
    end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController
  def new
     @ranking = Ranking.new
  end

  def edit
     @ranking = Ranking.find(params[:id])
  end

  def update
      @ranking = Ranking.find(params[:id])
     if @ranking.update_attributes(ranking_params)
      redirect_to @ranking
     else
      render 'edit'
     end
  end

  def index
      @rankings = Ranking.all
  end

  def show
       @ranking = Ranking.find(params[:id])
  end

  def create
     @ranking = Ranking.new(ranking_params)    
    if @ranking.save
      flash[:success] = "Ranking was added successfully!"
      redirect_to @ranking   
    else
      render 'new'
    end
  end
  
  def delete
  end

  def destroy
   Ranking.find(params[:id]).destroy
   flash[:success ]="Ranking Week deleted successively!"
   redirect_to rankings_url
  end

  def ranking_params
    params.require(:ranking).permit(:rankingTitle, :gender, :classification, :deadline, :publishDate, :voteTotal)
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def new
      @school = School.new
  end

  def create
     @school = School.new(school_params)    
    if @school.save
      flash[:success] = "School was added successfully!"
      redirect_to @school   
    else
      render 'new'
    end
  end

  def edit
    @school = School.find(params[:id])
  end
  
  def show
    @school = School.find(params[:id])
  end

  def update
     @school = School.find(params[:id])
     if @school.update_attributes(school_params)
      redirect_to @school
     else
      render 'edit'
     end
  end
  

   
 def index
  if params[:classification]
    @school = School.where(:classification => params[:classification])
  else
    @school = School.all
  end
 end
    
  
  
  def delete
  end

  def destroy 
   School.find(params[:id]).destroy
   flash[:success ]="School deleted successively!"
    redirect_to schools_url
  end

  
   private

    def school_params
      params.require(:school).permit(:schoolName, :displayName, :classification, :active,:cooperativeSchool)
    end
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rankers_helper.rb
module RankersHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
  
  def classForDisplay(classification)
    if (params[:classification] == classification && params[:classification].present?) 
      return "btn btn-default disabled"
    else
      return "btn btn-default"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
    <footer class="footer">
      <small>
        The IATC XC Ranking App<br />
        by WPU Software Engineering Class
      </small>
      <nav>
        <ul>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <li><a href="http://www.iatfcc.org/">IATFCC.org</a></li>
        </ul>
      </nav>
    </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-iatc-app" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Rank XC", root_path, class: "navbar-brand" %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-iatc-app">
          <ul class="nav navbar-nav">
            <li><%= link_to "Home", root_path %> <li>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Rankers", rankers_url %></li>
                <li><%= link_to "Schools", schools_url %></li>
                <li><%= link_to "Rankings", rankings_url %></li>
                <li><%= link_to "Votes", votes_url %></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | IATC XC Ranking App</title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
       <%= debug(params) if Rails.env.development? %>
    </div>
    
  </body>
</html>

app/views/rankers/edit.html.erb
<% provide(:title, "Edit Ranker") %>
<h1>Edit Ranker's Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="edit_ranker_form">
    <%= form_for @ranker, :html => {:class => "form-horizontal"} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :firstName , "First Name", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :firstName %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :lastName, "Last Name", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :lastName %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :email, class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.email_field :email %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :rankAccess, "Rank Access", class: "col-md-4 control-label" %>
      <div class="col-md-8">
        <%= f.text_field :rankAccess %>
      </div>
    </div>
    <div class="form-group">
      <div class="checkbox col-md-9 col-md-offset-3">
        <%= f.check_box :active %> Active?
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 text-right">
        <%= link_to "Save", "#", class: "btn btn-default btn-primary", :onclick => "$('#edit_ranker_form form').submit();"  %>
        <%= link_to "Delete", ranker_path(@ranker), method: :delete, data:{ confirm: 'are you sure you want to delete this ranker?'},class: "btn btn-primary" %>
        <%= link_to "Cancel", rankers_url, class: "btn btn-primary" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/rankers/index.html.erb
<% provide(:title, 'All rankers') %>

<h1>Rankers for the IATC XC Ranking System</h1>
 
<table class="table table-striped">

  <thead>
    <tr>
      <th>First Name </th> 
      <th>Last Name </th>
      <th>Classification</th>
      <th>Active?</th>
      <th colspan="2">Action</th>
    </tr>

  </thead>
 <tbody>
  <% @rankers.each do |ranker| %>
    <tr>
      <td><%= link_to ranker.firstName, ranker_path(ranker) %></td>
      <td><%= link_to ranker.lastName, ranker_path(ranker) %></td>
      <td><%= ranker.rankAccess %></td>
      <td>
        <% if ranker.active.to_i == 1 %>
          <i class="fa fa-check text-success"></i>
        <% else %>
          <i class="fa fa-times text-danger"></i>
        <% end %>
      </td>
      <td><%= link_to "edit", edit_ranker_path(ranker) %> </td>
      <td><%= link_to "delete", ranker_path(ranker), method: :delete, data:{ confirm: 'are you sure you want to delete this ranker?'} %> </td>

    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Add ranker", new_ranker_path, class: "btn btn-primary" %> 

app/views/rankers/new.html.erb
<% provide(:title, "New Ranker") %>
<h1>Add a new Ranker</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @ranker do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :firstName, "First Name" %>
      <%= f.text_field :firstName %>

      <%= f.label :lastName, "Last Name" %>
      <%= f.text_field :lastName %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.label :rankAccess %>
      <%= f.text_field :rankAccess %>
      
      <%= f.label :active %>
      <%= f.check_box :active  %>
      

      <%= f.submit "Create the Ranker", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/rankers/show.html.erb
<% provide(:title, 'Ranker Information') %>
<p><strong>Welcome <%= @ranker.firstName %> <%= @ranker.lastName %></strong></p>
  
<p><strong> Past Rankings</strong></p>
<table class="table table-striped">
<tr>2014</tr> 
<tr>
      <th>Week</th>
      <th>Gender</th> 
      <th>Classification</th>
      <th>Active</th>
</tr>
<tr>
      <td> Week 1</td>
      <td> Girls </td>
        <td> 2A </td>
        <td> <% if @ranker.active == 1  %>
              <i class="fa fa-check text-success"></i> Yes
            <% else %>
              <i class="fa fa-check text-danger"></i> No
            <% end %>
        </td>
    </tr>
   
</table>
  
<p><strong> Current Rankings</strong>  </p>
    
<table class="table table-striped">
 
<tr> 2016</tr> 
<tr>
      <th>Week</th>
      <th>Gender</th> 
      <th>Classification</th>
      <th>Active</th>
</tr>
<tr>
        <td> Week 4</td>
        <td> Boys </td>
        <td> 3A </td>
        <td> <% if @ranker.active == 1  %>
            <%=  "Yes" %>
            <% else %>
            <%=  "No" %>
            <% end %>
        </td>
</tr>
</table>
<h1>Example of sortable items</h1>
<ul id="sortable">
  <li class="ui-state-default">Pella</li>
  <li class="ui-state-default">Knoxville</li>
  <li class="ui-state-default">PCM</li>
  <li class="ui-state-default">Grinnell</li>
  <li class="ui-state-default">DCG</li>
  <li class="ui-state-default">Mount Pleasant</li>
  <li class="ui-state-default">Oskaloosa</li>
</ul>

app/views/rankings/create.html.erb
<h1>Rankings#create</h1>
<p>Find me in app/views/rankings/create.html.erb</p>

app/views/rankings/edit.html.erb
<% provide(:title, "Edit Rankings") %>
<h1>Edit Ranking's Information</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3" id="edit_rankings_form">
     <%= form_for @ranking do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

     <%= f.label :rankingTitle , "Ranking Title",class: "col-md-4 control-label"  %>
     <div class="col-md-8">
    <%= f.text_field :rankingTitle %>
    </div>
      
    <%= f.label :classification , "Classification",class: "col-md-4 control-label"  %>
    <div class="col-md-8">
    <%= f.select(:classification, options_for_select([['1A', '1A'],['2A', '2A'], ['3A', '3A'], ['4A', '4A']]))%>
     </div>
    <%= f.label :gender, "Gender",class: "col-md-4 control-label"  %> <br>
     <div class="col-md-8">
    <%= f.radio_button :gender, 'Male' %> Male<br />
    <%= f.radio_button :gender, 'Female' %> Female<br />
       </div>
    <%= f.label :deadline , "Deadline",class: "col-md-4 control-label"  %>
     <div class="col-md-8">
    <%= f.date_field :deadline %>
     </div>
    <%= f.label :publishDate , "publish Date",class: "col-md-4 control-label"  %>
    <div class="col-md-8">
    <%= f.date_field :publishDate %>
    </div>
    <%= f.label :voteTotal , "vote Total",class: "col-md-4 control-label" %>
    <div class="col-md-8">
    <%= f.text_field :voteTotal %>
 
   </div>
    <div class="col-xs-12 text-right">

     <%= link_to "Save", "#", class: "btn btn-default btn-primary", :onclick => "$('#edit_rankings_form form').submit();"  %>
        <%= link_to "Delete", ranking_path(@ranking), method: :delete, data:{ confirm: 'are you sure you want to delete this ranking?'},class: "btn btn-primary" %>
        <%= link_to "Cancel", rankings_url, class: "btn btn-primary" %>
       </div>
     
    <% end %>
      </div>
</div>

app/views/rankings/index.html.erb
<% provide(:title, 'All rankings') %>

<h1>Rankings for the IATC XC Ranking System</h1>
 
<table class="table table-striped">

  <thead>
    <tr>
      <th>Title </th> 
      <th>Gender</th>
      <th>Classification</th>
      <th>Deadline Date</th>
      <th colspan="2">Action</th>
    </tr>

  </thead>
 <tbody>
  <% @rankings.each do |ranking| %>
    <tr>
      <td><%= link_to ranking.rankingTitle, ranking_path(ranking) %></td>
      <td><%= ranking.gender %></td>
      <td><%= ranking.classification %></td>
      <td><%= ranking.deadline %></td>
      <td>
      <% if Time.current.to_date < ranking.deadline %>
        <%= link_to "edit", edit_ranking_path(ranking) %> 
        <%= link_to "delete", ranking_path(ranking), method: :delete, data:{ confirm: 'are you sure you want to delete this ranking?'} %> 
      <% end %>
      </td>

    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to "Add ranking", new_ranking_path, class: "btn btn-primary" %> 

app/views/rankings/new.html.erb
<% provide(:title, "Create Ranking") %>
<h1>Create a New Ranking</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3" id="edit_rankings_form">
     <%= form_for @ranking do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

     <%= f.label :rankingTitle , "Ranking Title",class: "col-md-4 control-label"  %>
        </div>
     <div class="col-md-8">
    <%= f.text_field :rankingTitle %>
    </div>
      
    <%= f.label :classification , "Classification",class: "col-md-4 control-label"  %>
    <div class="col-md-8">
    <%= f.select(:classification, options_for_select([['1A', '1A'],['2A', '2A'], ['3A', '3A'], ['4A', '4A']]))%>
     </div>
    <%= f.label :gender, "Gender",class: "col-md-4 control-label"  %> <br>
     <div class="col-md-8">
    <%= f.radio_button :gender, 'Male' %> Male<br />
    <%= f.radio_button :gender, 'Female' %> Female<br />
       </div>
    <%= f.label :deadline , "Deadline",class: "col-md-4 control-label"  %>
     <div class="col-md-8">
    <%= f.date_field :deadline %>
     </div>
    <%= f.label :publishDate , "publish Date",class: "col-md-4 control-label"  %>
    <div class="col-md-8">
    <%= f.date_field :publishDate %>
    </div>
    <%= f.label :voteTotal , "vote Total",class: "col-md-4 control-label" %>
    <div class="col-md-8">
    <%= f.text_field :voteTotal %>
 
      
    <%= f.submit "Create the Ranking", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/rankings/show.html.erb
<% provide(:title, 'Rankings Information') %>
<div class="row">
  <div class="col-sm-12"><h3>
      <%= @ranking.rankingTitle %></h3>
      <div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Classification:
  </div>
  <div class="col-sm-10 text-left">
    <%= @ranking.classification %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
   Gender:
  </div>
  <div class="col-sm-10 text-left">
    <%= @ranking.gender %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Deadline:
  </div>
  <div class="col-sm-10 text-left">
    <%= @ranking.deadline%>
  </div>
</div>

 <div class="row">
  <div class="col-sm-2 text-right">
    Publish Date:
  </div>
  <div class="col-sm-10 text-left">
    <%= @ranking.publishDate%>
  </div>
  
  <div class="row">
  <div class="col-sm-2 text-right">
    Vote Total:
  </div>
  <div class="col-sm-10 text-left">
    <%= @ranking.voteTotal%>
  </div>
  
  </div>
</div>

app/views/rankings/update.html.erb
<h1>Rankings#update</h1>
<p>Find me in app/views/rankings/update.html.erb</p>

app/views/schools/edit.html.erb
<% provide(:title, "Edit School") %>
<h1>Edit an existing school</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @school, :html => {:class => "form-horizontal"} do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    
      <%= f.label :schoolName , "School Name" %>
      <%= f.text_field :schoolName %>
      
      <%= f.label :displayName , "School Display Name" %>
      <%= f.text_field :displayName %>
       <%= f.label :classification , "Classification" %>
      <%= f.select(:classification, options_for_select([['1A', '1A'],['2A', '2A'], ['3A', '3A'], ['4A', '4A']]))%>
      
      <%= f.label :cooperativeSchool , "Cooperative School" %>
      <%= f.text_field :cooperativeSchool %>
      
      <%= f.label :active %>
      <%= f.check_box :active  %>

      <%= f.submit "update", class: "btn btn-primary" %>
      <%= link_to "delete", school_path(@school), method: :delete, data:{ confirm: 'are you sure you want to delete this school?'}, class: "btn btn-primary" %>
      <%= link_to "Cancel", schools_url, class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/schools/index.html.erb
<% provide(:title, 'All schools') %>

<h1>Schools for the IATC XC Ranking System</h1>
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <label class="control-label">Filter By: </label>
    <div class="btn-group" role="group">
      <%= link_to "1A", schools_path(:classification=>"1A"), class: classForDisplay("1A") %> 
      <%= link_to "2A", schools_path(:classification=>"2A"), class: classForDisplay("2A") %>
      <%= link_to "3A", schools_path(:classification=>"3A"), class: classForDisplay("3A") %>
      <%= link_to "4A", schools_path(:classification=>"4A"), class: classForDisplay("4A") %>
      <%= link_to "All", schools_url, class: "btn btn-default" %>
    </div>
  </div>
</div>
<% if (params[:classification] == "1A") %>
  <p>1A</p>
<% end %>

<table class="table table-striped">

  <thead>
           
    <tr>
      <th>School Name </th> 
      <th>Display Name </th>
      <th>Classification</th>
      <th>active</th>
      <th colspan="2">Action</th>
    </tr>

  </thead>
 <tbody>
  <% @school.each do |school| %>
    <tr>
      <td><%= link_to school.schoolName, school_path(school) %></td>
      <td><%= school.displayName %></td>
      <td><%= school.classification %></td>
      <td>
        <% if school.active.to_i == 1 %>
        <i class="fa fa-check text-success"></i>
        <% else %>
        <i class="fa fa-times text-danger"></i>
        <% end %>
      </td>
      <td><%= link_to "edit", edit_school_path(school) %> </td>
      <td><%= link_to "delete", school_path(school), method: :delete, data:{ confirm: 'are you sure you want to delete this school?'} %> </td>
  
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to "Add School", new_school_path, class: "btn btn-primary" %> 

app/views/schools/new.html.erb
<% provide(:title, "Create School") %>
<h1>Create a New School</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @school do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :schoolName , "School Name" %>
      <%= f.text_field :schoolName %>
      
      <%= f.label :displayName , "School Display Name" %>
      <%= f.text_field :displayName %>
      
      <%= f.label :classification , "Classification" %>
      <%= f.select(:classification, options_for_select([['1A', '1A'],['2A', '2A'], ['3A', '3A'], ['4A', '4A']]))%>
      <%= f.label :cooperativeSchool , "Cooperative School" %>
      <%= f.text_field :cooperativeSchool %>
      
      <%= f.label :active %>
      <%= f.check_box :active  %>
      
      <%= f.submit "Create the School", class: "btn btn-primary" %>
      
      <% end %>
  </div>
</div>

app/views/schools/show.html.erb
<% provide(:title, 'School Information') %>
<div class="row">
  <div class="col-sm-12"><h3><%= @school.schoolName %></h3><div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Classification:
  </div>
  <div class="col-sm-10 text-left">
    <%= @school.classification %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Display Name:
  </div>
  <div class="col-sm-10 text-left">
    <%= @school.displayName %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Cooperative:
  </div>
  <div class="col-sm-10 text-left">
    <%= @school.cooperativeSchool %>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 text-right">
    Active?:
  </div>
  <div class="col-sm-10 text-left">
    <% if @school.active.to_i == 1 %>
      <i class="fa fa-check text-success"></i> Yes
    <% else %>
      <i class="fa fa-times text-danger"></i> No
    <% end %>
  </div>
</div>

app/views/schools/update.html.erb
<h1>Schools#update</h1>
<p>Find me in app/views/schools/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About IATC Ranking App</h1>
<p>This app is designed to make the ranking of Iowa High School Cross Country 
teams easier to compile and share with media outlets.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact us</h1>
<p>Having issues? Want to send a comment? Email us at</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help For IATC XC Ranking App</h1>
<p>Need help?</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
    <h1>IATC XC RANKING</h1>
    <h2>Welcome to the IATC XC Ranking site. Rankings application will be coming soon.</h2>
    <%= link_to "Sign in now", "#", class: 'btn btn-primary btn-large' %>
</div>